dataset:
  name: "20newsgroups"
  categories: ["sci.space", "rec.autos", "talk.politics.misc", "comp.graphics"]
  remove: ["headers", "footers", "quotes"]

preprocess:
  lowercase: true
  remove_urls: true
  remove_html: true
  remove_punct: true
  keep_negations: true
  stopwords: "english"
  synonym_map:
    auto: car
    automobile: car
    automobiles: car
    autos: car
  lemmatize: true

features:
  vectorizer: "tfidf"
  ngram_range: [1, 2]
  max_df: 0.9
  min_df: 2
  max_features: 20000         # cap vocab so RF is fast

feature_selection:
  use_chi2: true
  k_best: 5000                # select top 5k features for RF

model:
  name: "RandomForest"
  n_estimators: 300
  max_depth: null
  max_features: "sqrt"
  n_jobs: -1
  random_state: 42

train:
  test_size: 0.2
  random_state: 42
